// Automatic Table Of Contents 0.1.1 (https://github.com/stevedoyle)
var c=(n,e)=>()=>(e||n((e={exports:{}}).exports,e),e.exports);var d=c((ee,k)=>{var g=class{},p={},v=class{},w=n=>n;if(A()){let n=require("obsidian");g=n.Plugin,p=n.MarkdownRenderer,v=n.MarkdownRenderChild,w=n.htmlToMarkdown}k.exports={Plugin:g,MarkdownRenderer:p,MarkdownRenderChild:v,htmlToMarkdown:w};function A(){return typeof process!="object"?!0:!process.env||!process.env.JEST_WORKER_ID}});var y=c((re,b)=>{var s={title:{type:"string",default:"## Table of Contents",comment:""},style:{type:"value",default:"nestedList",values:["nestedList","nestedOrderedList","inlineFirstLevel"],comment:"TOC style (nestedList|nestedOrderedList|inlineFirstLevel)"},minLevel:{type:"number",default:0,comment:"Include headings from the specified level"},maxLevel:{type:"number",default:0,comment:"Include headings up to the specified level"},include:{type:"regexp",default:null,comment:""},exclude:{type:"regexp",default:null,comment:""},includeLinks:{type:"boolean",default:!0,comment:"Make headings clickable"},hideWhenEmpty:{type:"boolean",default:!1,comment:"Hide TOC if no headings are found"},debugInConsole:{type:"boolean",default:!1,comment:"Print debug info in Obsidian console"}};b.exports={getOptionsDocs:P,parseOptionsFromSourceText:E};function P(){let n=[];for(let e of Object.keys(s)){let t=s[e],r=t.comment.length>0?` # ${t.comment}`:"",o=t.default!==null?t.default:"";n.push(`${e}: ${o}${r}`)}return n.join(`
`)}function E(n=""){let e={};for(let t of Object.keys(s))e[t]=s[t].default;for(let t of n.split(`
`)){let r=R(t);r!==null&&(e[r.name]=r.value)}return e}function R(n){let e=n.match(/([a-zA-Z0-9._ ]+):(.*)/);if(n.startsWith("#")||!e)return null;let t=e[1].trim(),r=s[t],o=e[2].trim();(!r||!["string","regexp"].includes(r.type))&&(o=o.replace(/#[^#]*$/,"").trim());let a=new Error(`Invalid value for \`${t}\``);if(r&&r.type==="number"){let i=Number.parseInt(o);if(i<0)throw a;return{name:t,value:i}}if(r&&r.type==="boolean"){if(!["true","false"].includes(o))throw a;return{name:t,value:o==="true"}}if(r&&r.type==="value"){if(!r.values.includes(o))throw a;return{name:t,value:o}}if(r&&r.type==="string")return o==="null"||o==='""'||o==="''"?{name:t,value:""}:{name:t,value:o};if(r&&r.type==="regexp"){if(o==="null"||o.length===0)return null;try{let i=/^\/(.*)\/([a-z]*)/.exec(o);if(!i)throw new Error("Invalid regexp");let l=new RegExp(i[1],i[2]);return{name:t,value:l}}catch{throw a}}return null}});var x=c((oe,L)=>{var{htmlToMarkdown:S}=d();L.exports={isHeadingAllowed:_,getFormattedMarkdownHeading:W};function _(n,e){return e.include?e.include.test(n):e.exclude?!e.exclude.test(n):!0}function W(n,e){if(e.includeLinks){let t=n;t=$(t),t=j(t),t=M(t,!1);let r=n;return r=M(r,!0),r=q(r),`[[#${r}|${t}]]`}return n}function $(n){return n.replaceAll("*","").replaceAll(/(\W|^)_+(\S)(.*?\S)?_+(\W|$)/g,"$1$2$3$4").replaceAll("`","").replaceAll("==","").replaceAll("~~","").replace(/\[([^\]]+)\]\([^)]+\)/g,"$1")}function j(n){return $(S(n))}function M(n,e){return n.replace(/\[\[([^\]]+)\|([^\]]+)\]\]/g,e?"$1 $2":"$2").replace(/\[\[([^\]]+)\]\]/g,"$1").replaceAll("[[","").replaceAll("| ",e?"":"- ").replaceAll("|",e?" ":"-")}function q(n){return n.replaceAll("#"," ")}});var T=c((le,H)=>{var{isHeadingAllowed:C,getFormattedMarkdownHeading:I}=x();H.exports={getMarkdownFromHeadings:N};function N(n,e){let t={nestedList:D,nestedOrderedList:B,inlineFirstLevel:z},r="";if(e.title&&e.title.length>0){let a=e.style==="inlineFirstLevel"?" ":`
`;r+=`${e.title}${a}`}let o=t[e.style](n,e);return o===null?e.hideWhenEmpty?"":`${r}_Table of contents: no headings found_`:r+o}function D(n,e){return O(n,!1,e)}function B(n,e){return O(n,!0,e)}function O(n,e,t){let r=e?"1.":"-",o=[],a=t.minLevel>0?t.minLevel:Math.min(...n.map(l=>l.level)),i=0;for(let l of n)if(!(i>0&&l.level>i)){if(l.level<=i&&(i=0),!C(l.heading,t)){i=l.level;continue}l.level<a||t.maxLevel>0&&l.level>t.maxLevel||l.heading.length!==0&&o.push(`${"	".repeat(l.level-a)}${r} ${I(l.heading,t)}`)}return o.length>0?o.join(`
`):null}function z(n,e){let t=e.minLevel>0?e.minLevel:Math.min(...n.map(o=>o.level)),r=n.filter(o=>o.level===t).filter(o=>o.heading.length>0).filter(o=>C(o.heading,e)).map(o=>I(o.heading,e));return r.length>0?r.join(" | "):null}});var{Plugin:J,MarkdownRenderer:F,MarkdownRenderChild:K}=d(),{getOptionsDocs:V,parseOptionsFromSourceText:Z}=y(),{getMarkdownFromHeadings:G}=T(),h="table-of-contents",Q="toc",m=class extends J{async onload(){let e=(t,r,o)=>{o.addChild(new f(this.app,r,o.sourcePath,t))};this.registerMarkdownCodeBlockProcessor(h,e),this.registerMarkdownCodeBlockProcessor(Q,e),this.addCommand({id:"insert-automatic-table-of-contents",name:"Insert table of contents",editorCallback:U}),this.addCommand({id:"insert-automatic-table-of-contents-docs",name:"Insert table of contents (with available options)",editorCallback:X})}};function U(n){let e=`\`\`\`${h}
\`\`\``;n.replaceRange(e,n.getCursor())}function X(n){let e=[`\`\`\`${h}
${V()}
\`\`\``];n.replaceRange(e.join(`
`),n.getCursor())}var f=class extends K{constructor(e,t,r,o){super(t),this.app=e,this.element=t,this.sourcePath=r,this.sourceText=o}onload(){this.render(),this.registerEvent(this.app.metadataCache.on("changed",this.onMetadataChange.bind(this)))}onMetadataChange(){this.render()}render(){try{let e=Z(this.sourceText);e.debugInConsole&&u("Options",e);let t=this.app.metadataCache.getCache(this.sourcePath),r=t?.headings?t.headings:[];e.debugInConsole&&u("Headings",r);let o=G(r,e);e.debugInConsole&&u("Markdown",o),this.element.empty(),F.renderMarkdown(o,this.element,this.sourcePath,this)}catch(e){let t=`_\u{1F4A5} Could not render table of contents (${e.message})_`;F.renderMarkdown(t,this.element,this.sourcePath,this)}}};function u(n,e){console.log(`%cAutomatic Table Of Contents %c${n}:
`,"color: orange; font-weight: bold","font-weight: bold",e)}module.exports=m;
